import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import { LoadingProvider } from "@/providers/LoadingProvider";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable}  antialiased`}
      >
        <TanstackQueryProvider>
          <LoadingProvider>
            <MainLayout>{children}</MainLayout>
          </LoadingProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
